name: Run UI & API Tests in Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test runner image
        run: docker build -t java-test-runner ./automation


      - name: Run tests inside Docker
        run: docker run --rm java-test-runner

